#!/bin/bash

choices="20%\n40%\n60%\n80%\n100%"

chosen=$(echo -e "$choices" | dmenu -p "Choose brightness level: ")

case "$chosen" in
	20%) xrandr --output eDP1 --brightness .2 ;;
	40%) xrandr --output eDP1 --brightness .4 ;;
	60%) xrandr --output eDP1 --brightness .6 ;;
	80%) xrandr --output eDP1 --brightness .8 ;;
	100%) xrandr --output eDP1 --brightness 1 ;;
esac
